- hosts: localhost
  roles:
    # - role: desktop-apps
    - role: console-apps
    - role: comcast.sdkman
      sdkman_user: daddyingrave
      sdkman_group: daddyingrave
      sdkman_auto_answer: true
      sdkman_update: true
      sdkman_install_packages:
        - { candidate: java, version: 8.0.232-librca }
        - { candidate: java, version: 11.0.5-librca }
        - { candidate: sbt, version: 1.3.4 }
        - { candidate: gradle, version: 6.0.1 }
      sdkman_defaults:
        java: 8.0.232-librca
        gradle: 6.0.1
        sbt: 1.3.4