- hosts: localhost
  become: yes
  roles:
#    - role: user
#    - role: console-apps
#      - role: graphics
#      - role: ui
#      - role: display-manager
#    - role: sound
#    - role: bluetooth
#    - role: desktop-apps
    - role: comcast.sdkman
      sdkman_user: "{{ user.name }}"
      sdkman_group: "{{ user.group }}"
      sdkman_auto_answer: true
      sdkman_update: true
      sdkman_install_packages:
        - { candidate: java, version: 8.0.252-librca }
        - { candidate: java, version: 11.0.7-librca }
        - { candidate: sbt }
        - { candidate: gradle }
      sdkman_defaults:
        java: 8.0.252-librca
  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
