---
- name: import 1password gpg key
  command: gpg --recv-key 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
  tags:
    - aur
    - dotfiles

- name: install 1password-cli
  become: yes
  become_user: "{{ user.name }}"
  aur:
    name: 1password-cli
    use: makepkg
    state: present
    skip_pgp_check: no
  tags:
    - aur
    - dotfiles
