---
- import_tasks: aur.yml

- name: install chezmoi
  pacman:
    name:
      - chezmoi
    state: present
  tags:
    - dotfiles

- name: login to 1password
  become: yes
  become_user: "{{ user.name }}"
  expect:
    command: op signin my.1password.com {{ user.email }}
    responses:
      question:
        - "{{ 1password_key }}"
        - "{{ 1password_password }}"
  tags:
    - dotfiles

#- name: login to 1password
#  become: yes
#  become_user: "{{ user.name }}"
#  onepassword:
#    secret_key: "{{ 1password_key }}"
#    master_password: "{{ 1password_password }}"
#  tags:
#    - dotfiles

#- name: apply dotfiles
#  become: yes
#  become_user: "{{ user.name }}"
#  command: chezmoi init --apply --verbose {{ dotfiles.url }}
#  tags:
#    - dotfiles
