---
- name: install PulseAudio bluetooth with LDAC/aptX support
  become: yes
  become_user: "{{ user.name }}"
  aur:
    name:
      - libldac
      - pulseaudio-modules-bt-git
    use: makepkg
    state: present
  tags:
    - aur
    - bluetooth
  notify:
    - restart pulse as user
