---
- name: install snapd
  become: yes
  become_user: "{{ user.name }}"
  aur:
    name: snapd
    use: makepkg
    state: present
  tags:
    - aur
    - desktop-apps

- name: install insync
  become: yes
  become_user: "{{ user.name }}"
  aur:
    name: insync
    use: makepkg
    state: present
  tags:
    - aur
    - desktop-apps

- name: install insync
  become: yes
  become_user: "{{ user.name }}"
  aur:
    name: jetbrains-toolbox
    use: makepkg
    state: present
  tags:
    - aur
    - desktop-apps
