---
- import_tasks: aur.yml

- name: install Okular
  pacman:
    name: okular
    state: present
  tags:
    - desktop-apps

- name: install insync repo key
  become: yes
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present
  tags:
    - snap
    - desktop-apps

- name: install spotify
  snap:
    name: spotify
    state: present
  tags:
    - snap
    - desktop-apps

- name: install postman
  snap:
    name: postman
    state: present
  tags:
    - snap
    - desktop-apps
