---
- import_tasks: aur.yml

- name: install Okular
  pacman:
    name: okular
    state: present
  tags:
    - desktop-apps

- name: install spotify
  snap:
    name: spotify
    state: present
  tags:
    - snap
    - desktop-apps

- name: install postman
  snap:
    name: postman
    state: present
  tags:
    - snap
    - desktop-apps
