---
- name: install everyday utils
  pacman:
    name:
      - git
      - curl
      - wget
      - htop
      - vim
      - jq
      - bash
      - bash-completion
      - zsh
      - zsh-completions
      - unzip
      - zip
      - ranger
      - sshpass
      - alacritty
    state: present
  tags:
    - console-apps

- import_tasks: oh-my-zsh.yml
- import_tasks: sdkman.yml
- import_tasks: aur.yml
