---
- name: add papirus repo
  become: yes
  apt_repository:
    repo: ppa:papirus/papirus


- name: install papirus
  become: yes
  apt:
    name: papirus-icon-theme
    state: present

- name: install everyday utils
  become: yes
  apt:
    name:
      - git
      - curl
      - wget
      - htop
      - net-tools
      - vim
      - jq
      - zsh
    state: present

- import_tasks: oh-my-zsh.yml