---
- name: cloning oh-my-zsh
  become: yes
  become_user: "{{ user.name }}"
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
  tags:
    - console-apps

- name: creating new ~/.zshrc
  become: yes
  become_user: "{{ user.name }}"
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
  tags:
    - console-apps

- name: set default shell for user
  become: yes
  become_user: "{{ user.name }}"
  user:
    name: "{{ user.name }}"
    shell: /bin/zsh
  tags:
    - console-apps

# https://askubuntu.com/questions/910821/programs-installed-via-snap-not-showing-up-in-launcher
- name: export all directories (for snap)
  become: yes
  become_user: "{{ user.name }}"
  lineinfile:
    path: /etc/zsh/zprofile
    regexp: "^emulate*"
    line: "emulate sh -c 'source /etc/profile'"
  tags:
    - console-apps

- name: set theme for zsh
  become: yes
  become_user: "{{ user.name }}"
  lineinfile:
    path: ~/.zshrc
    regexp: "^ZSH_THEME*"
    line: 'ZSH_THEME="avit"'
  tags:
    - console-apps
