---
- name: check if sdkman is installed
  become: yes
  become_user: "{{ user.name }}"
  shell: test -d /home/{{ user.name }}/.sdkman && echo "yes" || echo "no"
  register: is_sdkman_installed
  tags:
    - console-apps
    - sdkman

- name: install SDKMAN!
  become: yes
  become_user: "{{ user.name }}"
  when: is_sdkman_installed.stdout == "no"
  shell: curl -s http://get.sdkman.io | bash executable=/bin/zsh
  tags:
    - console-apps
    - sdkman

- name: ensure presence of bashrc
  become: yes
  become_user: "{{ user.name }}"
  file:
    state: touch
    path: "/home/{{ user.name }}/.zshrc"
  tags:
    - console-apps
    - sdkman

- name: add sdkman in .zshrc
  become: yes
  become_user: "{{ user.name }}"
  lineinfile:
    dest: "/home/{{ user.name }}/.zshrc"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {
        regexp: '.+SDKMAN_DIR.+',
        line: 'export SDKMAN_DIR="/home/{{ user.name }}/.sdkman"' }
    - {
        regexp: '\/.sdkman/bin\/sdkman\-init\.sh',
        line: '[[ -s "/home/{{ user.name }}/.sdkman/bin/sdkman-init.sh" ]] && source "/home/{{ user.name }}/.sdkman/bin/sdkman-init.sh"'
      }
  tags:
    - console-apps
    - sdkman
